name: Echo Changes

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  echo-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: List Changes
      run: |
        echo ${{ github.event.distinct_size }}
        echo ${{ github.event.before }}
        echo ${{ github.event.after }}
        echo ${{ github.event.ref }}
        git diff --name-only ${{ github.event.before }} ${{ github.event.head}} > test.txt; cat test.txt
