name: Identify Changed Files

on: push

jobs:
  identify-changed-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run which-files-changed
        uses: BuddhikaGeasman/which-files-changed@v.0.1.0-alpha
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr-comment: 'true' # or 'false' to control where to add the changes
