name: Echo Changes

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  echo-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: List Changes
      run: |
        echo ${{ github.event.ref}}
        git diff --name-only origin/main ${{ github.sha }} > test.txt; cat test.txt
