name: Identify Changed Files

on: push

jobs:
  identify-changed-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch HEAD and the commit before it
          fetch-depth: 2
        # Get the formatted line-by-line diff
      - id: get_diff
        uses: ILikePlayingGames/line-diff-action@v1.3
        with:
          commit-hash: '@~'
        # Read ./diff.txt in your next step to use the diff.
      - run: cat ./diff.txt;
